import { Quicksand as Font } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

import Provider from "@/hooks/providers";
import HeaderNav from "@/components/ui/navs/HeaderNav";
const inter = Font({ subsets: ["latin"] });
const font = localFont({src: "../fonts/nexa/Nexa-Light.ttf"})

export const metadata = {
  title: "UNSA Ethical Hacker Association",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className={font.className + " bg-fixed h-full"}>
        <Provider>
        
          {/* <HeaderNav /> */}
          {children}
        </Provider>
      </body>
    </html>
  );
}
