import { Inter } from "next/font/google";
import "./globals.css";

import Provider from "@/hooks/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "UNSA Ethical Hacker Association",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className={inter.className + " bg-fixed h-full"}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
